name: build-systemcmd5-openlane-sky130
on: [push]

jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: systemcmd5
      - name: Checkout pdk
        uses: actions/checkout@v2
        with:
          repository: olofk/pdklite
          path: pdklite
      - run: echo "PDK_ROOT=$GITHUB_WORKSPACE/pdklite" >> $GITHUB_ENV
      - run: echo "EDALIZE_LAUNCHER=${GITHUB_WORKSPACE}/openlane_runner.py" >> $GITHUB_ENV
      - run: pip3 install --user -e "git+https://github.com/olofk/edalize.git#egg=edalize"
      - run: pip3 install fusesoc
      - run: docker pull efabless/openlane:v0.12
      - run: wget https://raw.githubusercontent.com/olofk/subservient/main/openlane_runner.py
      - run: chmod +x openlane_runner.py
      - run: fusesoc library add md5 $GITHUB_WORKSPACE/systemcmd5
      - run: fusesoc run --target=sky130 systemcmd5
      
