name: build-systemcmd5-openlane-sky130
on: [push]

jobs:
  build-openlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: systemcmd5
      - name: Build with Openlane
        uses: librecores/ci-fusesoc-action@v1
        with:
          core: systemcmd5
          target: sky130
          tool: openlane

